### ISSUE TITLE
Bug when cycling logfiles

### ISSUE THREAD

**Issue by garrettseepersad** [semuconsulting/pygnssutils#29]
When cycling the logs, `_logpath` is overwritten and then creates a runtime error because the logpath had included the previous filename

**Problem**
```self._logpath = os.path.join(self._logpath, f"gnssntripclient-{tim}.log")```

**Solution**
```self._logfilepath = os.path.join(self._logpath, f"gnssntripclient-{tim}.log")```
```with open(self._logfilepath , "a", encoding="UTF-8") as log:```

**Comment by semuadmin** [comment]
Hi @garrettseepersad

Good shout, thanks. On it.
