### ISSUE TITLE
What is the "python 3 scripts (bin) folder"?

### ISSUE THREAD

**Issue by tlalexander** [semuconsulting/pygnssutils#33]
The readme says: 
"pygnssutils is compatible with Python >=3.8. It is recommended that the Python 3 scripts (bin) folder is in your PATH."

After installation I am unable to run the commands (I get "command not found"), so it seems this bin folder is not in my PATH.

I have tried to google for "python3 bin folder" and I am not finding any clear answer as to what that folder is or what its path should be on my debian system. I am about to go figure this out, but I wanted to suggest adding some clearer text here for future users. I also assume there is some way to run these commands without that folder being in the PATH, so some instructions on that as a fallback might also be helpful.

Thanks!

**Comment by tlalexander** [comment]
Ah for running it without knowing the path, I can just do:

python3 -m pygnssutils.gnssserver

So maybe that tip can be added to the readme.

I don't really know what's up with my system configuration that the script did not work the normal way, but I am going to move on to debugging my GPS issue. Thanks for this package and I hope my feedback is useful.

**Comment by semuadmin** [comment]
Hi @tlalexander 

Sorry you're having difficulties. These libraries do assume some prior knowledge of running Python scripts and modules.

You can normally choose the location of your Python bin/scripts folder during the installation procedure. Typically, the Python bin/scripts path will default to somewhere like this:

- Windows: `C:\Program Files\Python 3.11\scripts` or `C:\Users\username\AppData\Local\Programs\Python\Python3.11\scripts`
- MacOS: `/Library/Frameworks/Python.framework/Versions/3.11/bin/`
- Linux: `usr/bin` or `usr/local/bin`

On Linux, try running the command `which python3`.

The procedure for adding this location to your PATH also depends on the operating system and the terminal 'shell'  you're using (e.g. bash or zsh). 

- Windows: via the System Settings...Environment Variables panel.
- MacOS or Linux: by editing the shell resource configuration (rc) or profile file in your home directory e.g. .bashrc, .profile, .zshrc or .zprofile.


Running Python modules with the `-m` option is different to running scripts. The following tutorial might help:

[https://realpython.com/run-python-scripts/](https://realpython.com/run-python-scripts/)

**Comment by tlalexander** [comment]
Sure, thanks I have made a discussion.
https://github.com/semuconsulting/pygnssutils/discussions/34
