### ISSUE TITLE
Unable to receive RTCM Corrections using rtk_examples.py

### ISSUE THREAD

**Issue by acwu11** [semuconsulting/pygnssutils#5]
**Describe the bug**

Unable to receive RTCM corrections after following the rtk_examples.py on ZED_F9K receiver at baud rate of 38400. We replaced default fields with personal login for NTRIP client but cannot tell if 1) the NTRIP connection was unsuccessful or 2) the connection was successful but there is a problem in receiving RTCM corrections. 

From the 'NAV-SAT' message read from the receiver, the rtcmCorrUsed_xx field is always 0, but no additional error is thrown. 

Other information:

- pygnssutils version -- latest as of Oct. 14. 2022
- Sample output (after disabling the print messages from the "read thread") 
![image](https://user-images.githubusercontent.com/73973108/195948005-fa058b00-bb4d-47ee-bbce-528760afe38f.png)

* Expected Behavior * 
We expect to see a print field starting with "NTRIP >> ..." in the terminal when RTCM correction messages are received.

 * Desktop * 
- Operating System: Linux
- Type of Connection: USB

*GNSS/GPS Device: * 

- Device Model/Generation: u-blox ZED-F9K - 00B - 00
- Firmware Version: N/A
- Protocol: N/A.

**Comment by semuadmin** [comment]
Hi @acwu11 

Sorry you're having difficulties. I would be inclined to start with a basic gnssntripclient command line example first, just to establish if you're able to connect to the caster and receive RTCM data. Try the example here:  https://github.com/semuconsulting/pygnssutils#gnssntripclient.

First establish if you can download the caster's sourcetable (this is normally available without authentication):

`gnssntripclient server=rtgpsout.unavco.org reflat=55.3 reflon=-160.24 ggamode=1 verbosity=2`

where _55.3_ and _160.24_ are your fixed ARP reference coordinates (_substitute as appropriate_). You should see something like this in response:

```
2022-10-15 08:48:43.826172: Closest mountpoint to reference location (55.3, -160.24) = AB07_RTCM3, 16.17 km
2022-10-15 08:48:43.826265: Complete sourcetable follows...
['AB07_RTCM3', 'AB07_RTCM3', 'RTCM 3.1', '1004(1),1005(60),1007(60),1012(1),1033(60)', '2', 'GPS', 'UNAVCO', 'USA', '55.35', '-160.48', '0', '0', 'TRIMBLE NETRS', 'None', 'B', 'N', '0', '', '']
etc.
```

If this works, pick a suitable mountpoint MPT (e.g. _AB07_RTCM3_) and login credentials USERID/PASSWD and see if the caster returns valid RTCM data:

`gnssntripclient server=rtgpsout.unavco.org mountpoint=AB07_RTCM3 user=USERID password=PASSWD reflat=55.3 reflon=-160.24 ggamode=1 ggainterval=60 verbosity=2`

If authentication fails, you should see a corresponding `HTTP 401 Unauthorized error`. If all's well, you should see a stream of RTCM messages at the terminal.

Try this first and let me know how you get on.

**Comment by acwu11** [comment]
Hi @semuadmin 
Thanks! I tried these steps and was able to download the sourcetable. However, there was an authentication failure in the second step with terminal output :  HTTP/1.1 403 Forbidden. 

Does this indicate that it is a problem with the login? Would you have any suggested solution methods? For reference, we use the same credentials through u-center to establish the NTRIP Client.

**Comment by semuadmin** [comment]
> Hi @semuadmin Thanks! I tried these steps and was able to download the sourcetable. However, there was an authentication failure in the second step with terminal output : HTTP/1.1 403 Forbidden.
> 
> Does this indicate that it is a problem with the login? Would you have any suggested solution methods? For reference, we use the same credentials through u-center to establish the NTRIP Client.

Hi @acwu11 

Yes, an HTTP 403 error indicates an issue of some kind with authorisation issue (not necessarily with the login credentials). I would ordinarily expect an HTTP 401 if incorrect login credentials have been applied. An HTTP 403 _may_ indicate that the caster is applying some kind of block on the specific client IP address or application identifier.

`gnssntripclient` has been tested using casters which require basic authentication (userid and password) and it should work ok. I'm afraid I can't account for why it doesn't work in your case. I have applied for my own access credentials to the UNAVCO caster in order to test it myself, and am awaiting their response.

I take it the same caster, mountpoint and login credentials work fine in the u-center NTRIP client?

**Comment by acwu11** [comment]
@semuadmin 

Thanks in advance for checking with UNAVCO on your end. Just reverified and yes, the same caster, mountpoint, and login credentials work in u-center NTRIP client.

**Comment by semuadmin** [comment]
> @semuadmin
> 
> Thanks in advance for checking with UNAVCO on your end. Just reverified and yes, the same caster, mountpoint, and login credentials work in u-center NTRIP client.

@acwu11 I have now received and tested UNAVCO login credentials but I am getting the same error as you - an HTTP/1.1 403 Forbidden message. I have raised a query with UNAVCO but my best guess is that either a) their caster is blocking unrecognised NTRIP clients such as 'gnssntripclient', or b) my implementation of the NTRIP 2 protocol is somehow faulty (though, as I say, it works fine with many other authenticated casters). I'll continue to investigate.

**Comment by dborden0** [comment]
In the same example I am running into an error connecting to a local ntrip server that I have an account for. I get this error using the command line to connect:

D:\git\gps_rtk>poetry run gnssntripclient server=167.131.109.57 port=9882 user=user password=pwd mountpoint=IMAX_GG_RTCM3_AG waittime=20 verbosity=2 ggamode=1 ggainterval=60 reflat=42.38 reflon=-122.89
connected
data
b'HTTP/1.1 200 OK\r\nNtrip-Version: Ntrip/2.0\r\nCache-Control: no-store, no-cache, max-age=0\r\nPragma: no-cache\r\nServer: NTRIP Spider/7.8.0.9445\r\nDate: Wed, 19 Oct 2022 04:08:04 GMT\r\nConnection: close\r\nContent-Type: gnss/data\r\n\r\n'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\users\dbord\appdata\local\programs\python\python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\users\dbord\appdata\local\programs\python\python38-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\dbord\appdata\local\pypoetry\cache\virtualenvs\gps-rtk-o6opi8md-py3.8\lib\site-packages\pygnssutils\gnssntripclient.py", line 464, in _read_thread
    rc = self._do_header(self._socket, stopevent)
  File "c:\users\dbord\appdata\local\pypoetry\cache\virtualenvs\gps-rtk-o6opi8md-py3.8\lib\site-packages\pygnssutils\gnssntripclient.py", line 508, in _do_header
    data = sock.recv(DEFAULT_BUFSIZE)
socket.timeout: timed out

**Comment by dborden0** [comment]
Also, if I use the PyGPSClient with the same parameters, I receive data from the NTRIP server with no issues, which I believe uses the same NTRIP Client?

**Comment by wdimmit** [comment]
The UNAVCO caster seems to require `Connection: Close\r\n` be appended to the end of the GET request. See line 306 in `gnssntripclient.py`.  I'm not sure if this breaks compatibility with other casters, as I've only tested with UNAVCO.

**Comment by semuadmin** [comment]
> The UNAVCO caster seems to require `Connection: Close\r\n` be appended to the end of the GET request. See line 306 in `gnssntripclient.py`. I'm not sure if this breaks compatibility with other casters, as I've only tested with UNAVCO.

@wdimmit Many thanks for this - useful tip! Strange that this gives a 403 Forbidden rather than, say, a 400 Bad Request, but I'll certainly test this out. I take it the UNAVCO caster works fine with this fix?

**Comment by semuadmin** [comment]
@wdimmit 

Just tested gnssntripclient against `rtgpsout.unavco.org` with the following revised GET request:

```
        req = (
            f"GET {mountpoint} HTTP/1.1\r\n"
            + f"User-Agent: {USERAGENT}\r\n"
            + f"Host: {host}\r\n"
            + f"Authorization: Basic {user.decode(encoding='utf-8')}\r\n"
            + f"Ntrip-Version: Ntrip/{version}\r\n"
            + "Connection: close\r\n"  # required by some casters
        )
```

... but I'm still getting an `HTTP 403 Forbidden` using the login credentials that UNAVCO gave me. If I deliberately mistype the credentials I get an `HTTP 401 Unauthorized` instead, so I don't think it's a problem with the credentials.

Can you confirm that you're able to get a successful RTCM3 data stream from rtgpsout.unavco.org using gnssntripclient with your own credentials and location? Are you in close proximity to one of the mountpoints (_don't need to say which_)?

Out of interest, are you sending an NMEA GGA with the request (the NMEA flag in all the mountpoints on this caster seem to be set to '0' e.g. don't send a GGA)? I've tried with and without but no joy either way.

**Comment by semuadmin** [comment]
OK so finally got round to doing what I should have done in the first place - put a Wireshark intercept on the HTTP GET command from u-center's NTRIP client and compare it to mine:

![ucenter_GET](https://user-images.githubusercontent.com/28569967/206855701-90001a05-434b-43c1-8977-bbf34d6173d1.png)

Turns out the UNAVCO caster was objecting to my USERAGENT string for some reason. I've amended the string and it all appears to work fine now.
